#!/usr/bin/env bashio

bashio::log.info "Generating config.yml from options.json"
echo '# Generated by homeassistant, do not edit!' > /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml.tmp
echo '# Edit configuration only at the Add-on configuration tab!' >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml.tmp
json2yaml /data/options.json >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml.tmp
sed 's/  -/    -/'  /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml.tmp > /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
bashio::log.info "Configuration :"
bashio::log.info "$(cat /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml)"

debug=""
if $(bashio::config.true debug); then
    bashio::log.info "Will be started in debug mode"
    debug="-v"
fi

bashio::log.info "Image build"
bashio::log.info "starting original stuff..."
python3 /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/main.py $debug
