#!/usr/bin/env bashio

bashio::log.info "Generating config.yml from options.json"
echo '# Generated by homeassistant, do not edit!' > /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
echo '# Edit configuration only at the Add-on configuration tab!' >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
json2yaml /data/options.json >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
echo '  sites:' >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
echo '    - Maison' >> /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml
bashio::log.info "Configuration $(cat /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/config/config.yaml)"

bashio::log.info "Image build with version $(cat /version)"
bashio::log.info "starting original stuff..."
python3 /app/SomfyProtect2MQTT-dev/somfyProtect2Mqtt/main.py
